Makefile, README.dev, src/migration/seed.ts, src/model/bot_source_status.ts, src/model/bot_source_type.ts
- Add seeds 
- enum for bot_source_type
-  bot_source_status
- Fix CODEOWNERS file
=> Add seeds + enum for bot_source_type + bot_source_status

.github/CODEOWNERS, src/server/api/root.ts, src/server/api/routers/bot_source.ts, src/server/api/routers/post.ts
- Create bot source mock
- Get list bot source mock
- Update CODEOWNERS
=> Add bot source + get list

src/server/worker/bot_source_crawler.ts
=> Fix build err

src/server/api/root.ts, src/server/api/routers/bot.ts, src/server/api/routers/bot_integration.ts
=> feat: api get bot integrations

src/server/api/routers/bot.ts
=> fix: user could see all bots

src/components/BotSource/BotSource.tsx
Create UI for show source content detail
=> Create UI for show source content detail

src/migration/seed.ts, src/model/bot-model.ts, src/model/usage-limit-type.ts, src/server/api/routers/bot.ts, src/server/api/routers/chat.ts
- Add function signature for update bot settings
- Refactor seed file
=> chore: draft update bot function + refactor

src/components/BotSource/BotSource.tsx, src/components/BotSource/SourceLink.tsx
Integrate query source content detail API
=> Integrate query source content detail API

src/components/BotSource/BotSource.tsx
=> feat: integrate delete source API

src/server/api/root.ts, src/server/api/routers/ai-model.ts
=> feat: get ai model api

src/server/api/routers/bot-source.ts
- Delete old extracted data, vector when sync bot source
=> feat: clean old bot source data when re-sync bot source

src/components/BotSetting/BotDescription.tsx, src/components/BotSetting/BotLimit.tsx, src/components/BotSetting/BotMessages.tsx, src/components/BotSetting/BotModel.tsx, src/components/BotSetting/BotSetting.tsx
- The field "usageLimitPerUser" will be a string because the value of "SectionContent" component is a string. When you submit the form, we parse field "usageLimitPerUser" from string to a number.
=> feat: ui bot settings

src/components/BotSetting/BotMessages.tsx, src/components/BotSetting/BotSetting.tsx, src/server/api/routers/bot.ts, src/server/db/migration/schema.ts
- Update 2 field: noSourceWarningMsg and serverErrorMsg. You should be migrate to database,
=> feat: api update bot settings

src/server/api/routers/bot.ts
=> fix: change default value

Makefile
=> fix: makefile cmd db

src/server/api/routers/bot-source.ts
=> fix: missing delete extracted data vector

src/server/api/routers/chat.ts
- add user usage limit check for chat
=> feat: add limit usage check for chat

src/model/bot.ts, src/server/api/routers/bot.ts, src/server/db/migration/schema.ts
- add `api/trpc/bot.archive` api
curl
```
curl --location 'http://localhost:3000/api/trpc/bot.archive' \
--header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
--header 'Accept-Language: en-US,en;q=0.9' \
--header 'Cache-Control: max-age=0' \
--header 'Connection: keep-alive' \
--header 'Cookie: username-localhost-8888="2|1:0|10:1713695639|23:username-localhost-8888|196:eyJ1c2VybmFtZSI6ICIyODhhZTM5NzM5N2Q0NDdmYjQyOTQyYzFmOGJjNmE5NiIsICJuYW1lIjogIkFub255bW91cyBLYWx5a2UiLCAiZGlzcGxheV9uYW1lIjogIkFub255bW91cyBLYWx5a2UiLCAiaW5pdGlhbHMiOiAiQUsiLCAiY29sb3IiOiBudWxsfQ==|7d74a6e00106c0b661a3c984fcdc61e7c6d805d81e28a3caa99955d9f76ba1a2"; _xsrf=2|da632e84|f1e9adc6ea2025b9ef922c4b26ddb437|1713695639; …
```
=> feat: archive bot api

src/server/api/routers/bot-source.ts
- fix: delete sitemap bot source
=> fix: delete sitemap bot source

README.dev
=> chore: update README

src/server/api/routers/bot.ts, src/server/db/migration/schema.ts
-  My bad, I'm updating the default value wrong file. 
=> fix: set default description value

src/server/api/routers/bot-source.ts, src/server/api/routers/chat.ts, src/server/db/migration/schema.ts
=> feat: toggle visible for bot sources

src/components/BotSource/BotSource.tsx, src/components/BotSource/SourceDetailDrawer.tsx, src/server/api/routers/bot-source-extracted-data.ts, src/store/unsaved-changes.ts
- feat: add paging for get extracted data
=> feat: add paging for get extracted data

src/server/api/root.ts, src/server/api/routers/thread.ts
=> feat: create thread

src/components/Profile/Profile.tsx, src/components/Profile/ProfileName.tsx, src/components/Profile/index.ts, src/pages/profile.tsx, src/server/api/root.ts, src/server/api/routers/user.ts
=> feat: api update user profile

src/pages/bots/[id]/index.tsx, src/server/api/routers/chat.ts, src/utils/types.ts
- feat: require threadid when create chat
=> feat: require threadid when create chat

src/server/api/routers/thread.ts
- fix: type when create thread
=> fix: type when create thread

src/components/BotSource/FileDocSource.tsx, src/components/BotSource/SourceTable.tsx, src/components/FileInput/UploadFileModal.tsx, src/server/api/routers/bot-source.ts, src/server/db/migration/schema.ts
=> chore: add name for source bot

src/model/bot-source-type.ts, src/server/api/routers/bot-source.ts, src/server/db/migration/seed.ts
- crawl sitemap file
- Default types for get bot source
=> feat: crawl sitemap file

src/server/api/routers/bot-source.ts
=> feat: get sitemaps from url endpoint

src/model/bot-source-type.ts, src/server/api/routers/bot-source.ts
- Remove unused type: Sitemap file child
=> chore: remove unusued type

src/server/api/routers/chat.ts
=> feat: limit chat max length

package.json, src/components/AvatarUploader/AvatarUploader.tsx, src/components/AvatarUploader/index.ts, src/components/BotSetting/BotSetting.tsx, src/components/Profile/Profile.tsx, src/components/Profile/ProfileAvatar.tsx, src/components/layout/AuthLayout.tsx, src/server/api/routers/user.ts, src/server/db/migration/schema.ts
Update rendering firstName and lastName.
=> feat: upload avatar

src/server/api/routers/bot-source.ts
- fix: get main bot sources only
=> fix: get main bot sources only

src/components/BotSource/SourceDetailDrawer.tsx, src/server/api/routers/bot-source.ts
- fix: sitemap txt + get child bot sources
=> fix: sitemap txt + get child bot sources

src/server/api/routers/bot-source-extracted-data.ts
- feat: get bot source vector contents
=> feat: get bot source vector contents

src/components/BotSetting/BotSetting.tsx, src/components/common/FormSkeleton.tsx
=> fix: error message and load skeleton when initial data

src/components/layout/AuthLayout.tsx, src/pages/bots/[id]/index.tsx, src/server/api/routers/thread.ts
=> feat: map appearance settings to chat thread

src/components/AvatarUploader/AvatarUploader.tsx, src/components/BotAppearance/BotAppearance.tsx, src/components/BotAppearance/BotAvatarWidget.tsx, src/components/BotAppearance/BotCompanyLogo.tsx
=> refactor: form pattern and mutation callback handle

src/components/layout/AuthLayout.tsx
- Handle call to the api to get an attachment.
=> fix: handle call api get attachment

src/app/api/sync-bot-source/route.ts
- It'll cover the title or heading to the relevant chunk.
=> fix: separator splitting

src/app/api/sync-bot-source/route.ts
- fix: maxDuration not working
=> fix: maxDuration not working

src/server/api/routers/chat.ts
- Separate logic build prompt.
- When length of getRelatedContext > 0  => Build prompt => AskAI.
- When length of getRelatedContext < 0 return noRelevantContextMsg.
=> feat: handle no context relevant

src/server/api/routers/bot.ts
- Get data of bot appearance by apiToken. 
- You can testing this api following code below: 
```
const { data: getBotAppearanceSettingByApiToken } =
api.bot.getBotAppearanceSettingByApiToken.useQuery({
apiToken: '',
})
console.log(getBotAppearanceSettingByApiToken)
```
=> feat: get bot appearance by apiToken

src/pages/bots/[id]/index.tsx, src/server/api/routers/chat.ts
- List the links that have content similarity.
=> feat: refer source links

src/pages/bots/[id]/index.tsx, src/server/api/routers/chat.ts
=> feat: refer source links (#105)

src/pages/bots/[id]/index.tsx
- Fix open new tab when click url.
=> fix: open new tab when click url

src/components/Profile/Profile.tsx, src/components/Profile/ProfileAvatar.tsx, src/components/Profile/ProfileName.tsx
- Form pattern when load data and return default profile data to form provider.
=> refactor: form pattern

src/components/Knowledge/KnowledgeSearch.tsx, src/components/Knowledge/KnowledgeSettings.tsx, src/components/Knowledge/RetrievalSearchCard.tsx, src/server/api/core/rag/retrieval/search-method.ts, src/server/api/core/types/retrieval-model.ts, src/server/api/routers/bot-source.ts, src/server/api/routers/chat.ts, src/server/api/routers/retrieval.ts
- Fix calculates RRF scores. 
- Add 2 props to handle vector weight and full-text weight.
=> fix: rrf method and config vector weight and full-text weight

src/server/db/migration/schema.ts
- Fix typo, we should run migrate schema.
=> fix: typo schema

src/components/BotSource/SourceTypeBadge.tsx, src/components/Knowledge/KnowledgeSearch.tsx, src/components/Knowledge/KnowledgeSettings.tsx, src/components/Knowledge/RetrievalSearchCard.tsx, src/server/api/core/rag/retrieval/search-method.ts, src/server/api/core/types/retrieval-model.ts, src/server/api/routers/bot-source.ts, src/server/api/routers/chat.ts, src/server/api/routers/retrieval.ts, src/server/db/migration/schema.ts
- Change UI to set alpha 
- Chore fix: length submit form retrieval search, remove ::vector not necessary. 
- Change create hnsw index using query to function.
=> fix: alpha retrieval setting and ui
